# Generated by Django 6.1 on 2026-08-08 00:30

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('streak', models.PositiveIntegerField(default=0, help_text='Current consecutive-day streak, protected by readiness.')),
                ('avatar', models.URLField(blank=True, default='https://api.dicebear.com/7.x/avataaars/svg?seed=Flamingo', help_text='Avatar image URL shown on leaderboards and the dashboard.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.PositiveIntegerField(default=0)),
                ('energy', models.PositiveIntegerField(default=0)),
                ('time_speedups', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('garmin', 'Garmin'), ('peloton', 'Peloton'), ('liftosaur', 'Liftosaur'), ('home_assistant', 'Home Assistant')], max_length=20)),
                ('event_type', models.CharField(help_text='e.g. cardio, strength, sleep, body_battery, macro, scale', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=core.models.default_now)),
                ('processed', models.BooleanField(default=False, help_text='True once the XP service has converted this log to XP.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.PositiveIntegerField(help_text='0-100 readiness score computed from sleep + body battery.')),
                ('streak_requirement', models.CharField(choices=[('rest_day', 'Rest Day'), ('train', 'Train')], default='train', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('body_battery', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_readiness')],
            },
        ),
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('nutrition', 'Nutrition'), ('recovery', 'Recovery')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0, help_text='XP accumulated *within* the current level (0..XP_PER_LEVEL).')),
                ('total_xp', models.PositiveIntegerField(default=0, help_text='Lifetime XP in this modality (drives level ups).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['modality'],
                'constraints': [models.UniqueConstraint(fields=('user', 'modality'), name='unique_user_modality')],
            },
        ),
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('garmin', 'Garmin'), ('peloton', 'Peloton'), ('liftosaur', 'Liftosaur'), ('home_assistant', 'Home Assistant')], max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='OAuth tokens / API keys for this provider.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider')],
            },
        ),
        migrations.CreateModel(
            name='XPLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('nutrition', 'Nutrition'), ('recovery', 'Recovery')], max_length=20)),
                ('amount', models.IntegerField(help_text='Positive XP award. Negative entries possible for corrections.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_entries', to='core.rawactivitylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_xpledg_user_id_2bda66_idx'), models.Index(fields=['modality'], name='core_xpledg_modalit_7f9b7e_idx')],
            },
        ),
    ]
