# Generated by Django 6.1 on 2026-08-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawactivitylog',
            name='source',
            field=models.CharField(choices=[('garmin', 'Garmin'), ('peloton', 'Peloton'), ('liftosaur', 'Liftosaur'), ('sparkyfitness', 'SparkyFitness'), ('home_assistant', 'Home Assistant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='provider',
            field=models.CharField(choices=[('garmin', 'Garmin'), ('peloton', 'Peloton'), ('liftosaur', 'Liftosaur'), ('sparkyfitness', 'SparkyFitness'), ('home_assistant', 'Home Assistant')], max_length=20),
        ),
    ]
