# Generated by Django 6.1 on 2026-08-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rawactivitylog_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Boss name, e.g. 'Bench Press'.", max_length=120)),
                ('exercise_match', models.CharField(help_text="Substring matched (case-insensitive) against Liftosaur exercise names, e.g. 'Bench Press'.", max_length=120)),
                ('bodyweight_multiplier', models.FloatField(default=1.5, help_text='Lift goal = bodyweight x multiplier (e.g. 1.5x BW).')),
                ('unit', models.CharField(default='lb', help_text='lb or kg', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='modality',
            field=models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('recovery', 'Recovery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='xpledger',
            name='modality',
            field=models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('recovery', 'Recovery')], max_length=20),
        ),
    ]
