# Generated by Django 6.1 on 2026-08-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bossconfig_alter_skilltree_modality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBuildingDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-umbrella-beach', max_length=40)),
                ('base_cost_materials', models.PositiveIntegerField(default=40)),
                ('base_cost_energy', models.PositiveIntegerField(default=10)),
                ('base_duration_hours', models.PositiveIntegerField(default=6, help_text='0 = instant micro-build.')),
                ('materials_per_day', models.PositiveIntegerField(default=0)),
                ('xp_bonus_pct', models.PositiveIntegerField(default=0)),
                ('max_level', models.PositiveIntegerField(default=5)),
                ('requires_base_level', models.PositiveIntegerField(default=0)),
                ('requires_blueprint', models.CharField(blank=True, help_text="e.g. 'golden_flamingo' - must be owned in BaseResource.blueprints.", max_length=50, null=True)),
                ('modality_affinity', models.CharField(blank=True, help_text="e.g. 'strength' / 'cardio' - matches an active_buffs key for 1.2x production.", max_length=20, null=True)),
                ('branch_choices', models.JSONField(default=dict, help_text="Level-3 evolution menu, e.g. {'Materials': 'cabana_mat', 'XP': 'cabana_xp'}.")),
                ('rest_day_bonus_add', models.PositiveIntegerField(default=0, help_text='Extra rest-day energy granted while this building is owned (Recovery Pool).')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='baseresource',
            name='active_buffs',
            field=models.JSONField(default=dict, help_text="Modality production buffs, e.g. {'strength_buff_expiry': 'iso-date'}."),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='blueprints',
            field=models.JSONField(default=dict, help_text="Rare blueprint ownership, e.g. {'golden_flamingo': 1} (unlocks prestige defs)."),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='energy_updated_at',
            field=models.DateTimeField(blank=True, help_text='Passive energy regen checkpoint (never stored while above the cap).', null=True),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='last_daily_harvest',
            field=models.DateField(blank=True, help_text='Last date the daily XP -> materials dividend was minted (idempotency).', null=True),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='last_milestone_celebrated',
            field=models.IntegerField(default=0, help_text='Base level whose confetti celebration was acknowledged (5, 10, ...).'),
        ),
        migrations.AddField(
            model_name='baseresource',
            name='last_rest_bonus_date',
            field=models.DateField(blank=True, help_text='Last date the rest-day energy spike was granted (idempotency).', null=True),
        ),
        migrations.CreateModel(
            name='BaseBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, help_text='Built level (0 = never built).')),
                ('target_level', models.PositiveIntegerField(default=0, help_text='In-construction target level.')),
                ('construction_started_at', models.DateTimeField(blank=True, null=True)),
                ('construction_duration_hours', models.PositiveIntegerField(default=0)),
                ('last_produced_at', models.DateTimeField(blank=True, help_text='Idle-accrual checkpoint for production.', null=True)),
                ('custom_color', models.CharField(default='#FF69B4', help_text='Neon customization (#RRGGBB).', max_length=7)),
                ('staff_friend_id', models.IntegerField(blank=True, help_text='Social +10% production boost avatar id.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_buildings', to=settings.AUTH_USER_MODEL)),
                ('building_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.basebuildingdef')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'building_def'), name='unique_user_building_def')],
            },
        ),
    ]
