# Generated by Django 6.1 on 2026-08-14 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_basebuildingdef_baseresource_active_buffs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, help_text='Shown on the badge tile.', max_length=255)),
                ('icon', models.CharField(default='fa-medal', help_text="FontAwesome icon class, e.g. 'fa-fire' (no 'fa-solid' prefix).", max_length=60)),
                ('category', models.CharField(default='Milestones', max_length=40)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive badges are hidden from players.')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.badgedef')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge')],
            },
        ),
    ]
