# Generated by Django 6.1 on 2026-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_achievement_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgedef',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Badge Points awarded for earning this badge (scale by difficulty).'),
        ),
        migrations.AddField(
            model_name='badgedef',
            name='rule',
            field=models.JSONField(blank=True, default=dict, help_text='Declarative earn rule evaluated by core/services/badges.py, e.g. {"type": "streak", "minimum": 30}. See the README "Achievement badges" section for all rule types. An empty rule can never be earned.'),
        ),
    ]
