# Generated by Django 6.1 on 2026-08-16 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Weightlifting'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('sleep', 'Sleep')], max_length=20)),
                ('date', models.DateField()),
                ('base_damage', models.BigIntegerField(default=0)),
                ('gear_multiplier', models.FloatField(default=1.0)),
                ('boss_multiplier', models.FloatField(default=1.0)),
                ('total_damage', models.BigIntegerField(default=0)),
                ('boss_heal', models.BigIntegerField(default=0)),
                ('tokens_won', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Weightlifting'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('sleep', 'Sleep')], max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(default='fa-dragon', max_length=60)),
                ('hp_total', models.BigIntegerField(default=100000)),
                ('element', models.CharField(choices=[('endurance', 'Endurance'), ('strength', 'Strength'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('recovery', 'Recovery')], max_length=20)),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='Campaign domains dealing 2x damage.')),
                ('resistances', models.JSONField(blank=True, default=list, help_text='Campaign domains dealing 0.5x damage.')),
                ('mechanics', models.JSONField(blank=True, default=dict, help_text='{"front_load_water_noon": true, "heal_on_overage": true}.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['campaign', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Weightlifting'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('sleep', 'Sleep')], max_length=20)),
                ('damage_dealt', models.BigIntegerField(default=0)),
                ('total_hp', models.BigIntegerField(default=0)),
                ('conquered', models.BooleanField(default=False)),
                ('engaged_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GearItemDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slot', models.CharField(blank=True, choices=[('head', 'Head'), ('body', 'Body'), ('accessory', 'Accessory')], default='', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('effect_type', models.CharField(default='domain_multiplier', help_text='domain_multiplier | synergy | double_domain | shield_overage. Consumables use double_domain / shield_overage.', max_length=30)),
                ('effect_domain', models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('strength', 'Weightlifting'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('sleep', 'Sleep')], max_length=20, null=True)),
                ('effect_value', models.FloatField(default=1.0)),
                ('requires_sleep_efficiency', models.FloatField(blank=True, help_text='e.g. 0.85 gates a synergy item.', null=True)),
                ('weight', models.PositiveIntegerField(default=100, help_text='Relative drop weight in a pack.')),
                ('is_consumable', models.BooleanField(default=False)),
                ('max_stack', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(default='fa-helmet-battle', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='GearPackDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-box-open', max_length=60)),
                ('price_tokens', models.PositiveIntegerField(default=100)),
                ('draws', models.PositiveIntegerField(default=1)),
                ('domains', models.JSONField(blank=True, default=list, help_text='Targeted Campaign values.')),
                ('guaranteed_min_rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('terrain', models.CharField(choices=[('endurance', 'Endurance'), ('strength', 'Strength'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration'), ('recovery', 'Recovery')], default='strength', max_length=20)),
                ('defense_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen loadout + 7-day consistency used for async resolution.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_until', models.DateTimeField()),
                ('last_token_paid', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.PositiveIntegerField(default=300, help_text='Premium currency spent in the Gacha Shop.')),
                ('stamina', models.PositiveIntegerField(default=3, help_text='Daily siege-attack budget (refills each day).')),
                ('stamina_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_token_harvest', models.DateField(blank=True, help_text='Daily token-dividend idempotency stamp.', null=True)),
                ('active_buffs', models.JSONField(default=dict, help_text="Dated combat buffs, e.g. {'cardio_double_date': 'YYYY-MM-DD'.")),
                ('total_conquests', models.PositiveIntegerField(default=0)),
                ('pvp_wins', models.PositiveIntegerField(default=0)),
                ('pvp_losses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PvPMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_power', models.FloatField(default=0.0)),
                ('defender_power', models.FloatField(default=0.0)),
                ('did_win', models.BooleanField(default=False)),
                ('token_stake', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('equipped_slot', models.CharField(blank=True, choices=[('head', 'Head'), ('body', 'Body'), ('accessory', 'Accessory')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-obtained_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='basebuilding',
            name='unique_user_building_def',
        ),
        migrations.AddField(
            model_name='battlelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignprogress',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaignboss'),
        ),
        migrations.AddField(
            model_name='campaignprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gearitemdef',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.gearpackdef'),
        ),
        migrations.AddField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymoccupation',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='core.gym'),
        ),
        migrations.AddField(
            model_name='gymoccupation',
            name='occupant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_turf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvpmatch',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_attacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvpmatch',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_defenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvpmatch',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.gym'),
        ),
        migrations.AddField(
            model_name='usergear',
            name='gear_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='core.gearitemdef'),
        ),
        migrations.AddField(
            model_name='usergear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='basebuilding',
            name='building_def',
        ),
        migrations.RemoveField(
            model_name='basebuilding',
            name='user',
        ),
        migrations.DeleteModel(
            name='BaseResource',
        ),
        migrations.AddConstraint(
            model_name='campaignprogress',
            constraint=models.UniqueConstraint(fields=('user', 'campaign'), name='unique_user_campaign'),
        ),
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_gym_owner'),
        ),
        migrations.DeleteModel(
            name='BaseBuildingDef',
        ),
        migrations.DeleteModel(
            name='BaseBuilding',
        ),
    ]
