# Generated by Django 6.1 on 2026-08-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_phase9'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearpackdef',
            name='is_generic',
            field=models.BooleanField(default=False, help_text='Crate-style pack that drops from the whole gear catalog (ignores the pack FK).'),
        ),
        migrations.AlterField(
            model_name='gearitemdef',
            name='icon',
            field=models.CharField(default='fa-shirt', max_length=60),
        ),
        migrations.AlterField(
            model_name='leagueresult',
            name='reward',
            field=models.JSONField(blank=True, default=dict, help_text='Rewards paid on close, e.g. {"tokens": 5}.'),
        ),
    ]
