# Generated by Django 6.1 on 2026-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gearpackdef_is_generic_alter_gearitemdef_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitemdef',
            name='slot',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('chest', 'Chest'), ('left_hand', 'Left Hand'), ('right_hand', 'Right Hand'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usergear',
            name='equipped_slot',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('chest', 'Chest'), ('left_hand', 'Left Hand'), ('right_hand', 'Right Hand'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], max_length=20, null=True),
        ),
    ]
