# Generated by Django 6.1 on 2026-08-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_gearitemdef_slot_alter_usergear_equipped_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitemdef',
            name='effect_params',
            field=models.JSONField(blank=True, default=dict, help_text="Extensible JSON for richer effects, e.g. {'scales_from': 'strength'} for effect_type=scales_with."),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_scraps_stamp',
            field=models.DateField(blank=True, help_text='Scrap-shop rotation idempotency stamp.', null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='scraps',
            field=models.PositiveIntegerField(default=0, help_text='Scrap currency earned by recycling gear; spent in the Scrap Shop.'),
        ),
        migrations.CreateModel(
            name='ScrapShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(default='fa-box-open', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('cost_scraps', models.PositiveIntegerField(default=50)),
                ('available_days', models.JSONField(blank=True, default=list, help_text='date.weekday() ints (0=Mon..6=Sun) this item is offered.')),
                ('reward_type', models.CharField(choices=[('tokens', 'Tokens'), ('stamina', 'Stamina'), ('pack', 'Pack draws')], default='tokens', max_length=20)),
                ('reward_value', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gearpackdef')),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
    ]
