# Generated by Django 6.1 on 2026-08-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gearitemdef_effect_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlelog',
            name='boss',
            field=models.ForeignKey(blank=True, help_text='The specific boss this attack hit (docs/17 #33/#34 sieges).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_logs', to='core.campaignboss'),
        ),
    ]
