# Generated by Django on 2026-08-19 - docs/17 #91 (Guided first-flight onboarding)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_battlelog_boss_docs1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="onboarded",
            field=models.BooleanField(
                default=False,
                help_text="Guided first-flight onboarding completed (docs/17 #91).",
            ),
        ),
    ]