# Generated by Django 6.1 on 2026-08-23 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_playerprofile_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='source_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences for data provider per modality.'),
        ),
        migrations.AlterField(
            model_name='rawactivitylog',
            name='source',
            field=models.CharField(choices=[('garmin', 'Garmin'), ('peloton', 'Peloton'), ('liftosaur', 'Liftosaur'), ('sparkyfitness', 'SparkyFitness'), ('home_assistant', 'Home Assistant'), ('health_connect', 'Health Connect'), ('healthkit', 'HealthKit'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='provider',
            field=models.CharField(choices=[('garmin', 'Garmin'), ('peloton', 'Peloton'), ('liftosaur', 'Liftosaur'), ('sparkyfitness', 'SparkyFitness'), ('home_assistant', 'Home Assistant'), ('health_connect', 'Health Connect'), ('healthkit', 'HealthKit'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('price_type', models.CharField(choices=[('tokens', 'Tokens'), ('scraps', 'Scraps')], default='tokens', max_length=10)),
                ('price_amount', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_purchases', to=settings.AUTH_USER_MODEL)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='core.gearitemdef')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
                ('user_gear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_entries', to='core.usergear')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
