# Generated by Django 6.1 on 2026-08-23 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_playerprofile_source_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Push notification settings per category and quiet hours.'),
        ),
        migrations.AlterField(
            model_name='scrapshopitem',
            name='reward_type',
            field=models.CharField(choices=[('tokens', 'Tokens'), ('stamina', 'Stamina'), ('pack', 'Pack draws'), ('streak_freeze', 'Streak Freeze')], default='tokens', max_length=20),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food & Meals'), ('hydration', 'Hydration'), ('workout', 'Workout & Activity'), ('sleep', 'Sleep & Wind-down'), ('streak', 'Streak Preservation'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
