# Generated by Django 6.1 on 2026-08-23 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_playerprofile_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationlog',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Meals'), ('hydration', 'Hydration'), ('workout', 'Workout & Activity'), ('sleep', 'Sleep & Wind-down'), ('streak', 'Streak Preservation'), ('bounty', 'Bounties & Duels'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty_type', models.CharField(choices=[('solo', 'Solo Contract'), ('open', 'Open Board Bounty'), ('duel', '1v1 Duel'), ('flock', 'Flock Raid Bounty')], default='open', max_length=15)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('steps', 'Steps'), ('cardio_minutes', 'Cardio Minutes'), ('strength_volume', 'Strength Volume (lbs)'), ('water_ml', 'Hydration (ml)'), ('protein_g', 'Protein (g)'), ('calories_burned', 'Active Calories Burned'), ('workout_count', 'Workouts Logged'), ('sleep_hours', 'Sleep (Hours)')], max_length=25)),
                ('target_value', models.FloatField(help_text='Target numerical goal (e.g. 10000 steps, 25000 lbs, 3000 ml water).')),
                ('wager_tokens', models.PositiveIntegerField(default=0, help_text='Tokens staked per participant in escrow.')),
                ('wager_scraps', models.PositiveIntegerField(default=0, help_text='Scraps staked per participant in escrow.')),
                ('reward_xp', models.PositiveIntegerField(default=50, help_text='XP awarded upon verified completion.')),
                ('bonus_tokens', models.PositiveIntegerField(default=10, help_text='System-funded bonus tokens added to prize pool.')),
                ('status', models.CharField(choices=[('open', 'Open (Awaiting Opponent)'), ('active', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='Duration in hours from when bounty becomes active.')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False, help_text='True once winner has claimed prize pot.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties_created', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flock_bounties', to='core.flock')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties_challenged', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(default=0.0, help_text='Total verified progress logged during active window.')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_claimed', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.bounty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('bounty', 'user'), name='unique_bounty_participant')],
            },
        ),
    ]
