"""Service layer for Flamingo Fitness.

Exposes the gamification and readiness engines to views, tasks and admin.
"""

from .api_clients import (  # noqa: F401
    GarminClient,
    PelotonClient,
    get_client,
)
from .sparky_client import SparkyFitnessClient  # noqa: F401
from .liftosaur_client import LiftosaurClient  # noqa: F401
from .gamification import (  # noqa: F401
    XP_PER_LEVEL,
    calorie_xp,
    hydration_tokens,
    hydration_xp,
    nutrition_tokens,
    nutrition_xp,
    process_log,
    process_payload,
    protein_xp,
    sleep_xp,
    summarize_endurance,
    summarize_hydration,
    summarize_nutrition,
    summarize_sleep,
    summarize_strength,
)
from .readiness import (  # noqa: F401
    compute_readiness,
    compute_readiness_for_all_users,
)
from .combat import (  # noqa: F401
    BOSS_HEAL_OVERAGE,
    BOSS_HP_SCALE,
    BULK_DISCOUNTS,
    BULK_MAX,
    CONSUMABLE_MAX_STACK,
    ELEMENT_WHEEL,
    EPIC_STREAK_STEP,
    GEAR_MULT_POOL,
    GYM_HOLD_WINDOW_HOURS,
    GYM_TOKEN_YIELD_BASE,
    HEAD_SLOT,
    LEGENDARY_STREAK_STEP,
    PACK_PRICE_DELUXE,
    PACK_PRICE_LEGENDARY,
    PACK_PRICE_SIMPLE,
    PVP_AGGRESSOR_WIN_EDGE,
    PVP_CONSISTENCY_WINDOW_DAYS,
    RARITY_WEIGHTS_BASE,
    REST_DAY_STAMINA_BONUS,
    SLOT_ORDER,
    STAMINA_PER_DAY,
    STREAK_ODDS_START_DAY,
    SYNERGY_SLEEP_EFF,
    TOKEN_BOSS_PR,
    TOKEN_MATERIAL_RATE,
    TOKEN_PERFECT_HYDRATION,
    TOKEN_PERFECT_MACRO,
    TOKEN_PVE_CONQUEST,
    TOKEN_STARTER,
    TOKEN_TIME_SPEEDUP_RATE,
    XP_TO_TOKENS,
    attack_boss,
    attack_gym,
    attacker_power,
    active_buff_multiplier,
    award_tokens,
    additive_bonus,
    base_damage_for,
    battle_history,
    battle_leaderboard,
    battle_state,
    boss_vulnerability,
    bulk_price,
    buy_scrap_item,
    clear_expired_buffs,
    consume_consumable,
    daily_token_harvest,
    engage_boss,
    open_pack,
    open_pack_bulk,
    pay_gym_yields,
    power_breakdown,
    profile,
    pvp_state,
    rarity_weights,
    recycle_gear,
    refresh_stamina,
    scrap_shop_state,
    scrap_value,
    set_defense,
    spend_tokens,
    stamina_cap,
    stat_breakdown_for,
    streak_multiplier,
    tick_combat_daily,
    token_dividend,
    token_dividend_multiplier,
    total_gear_multiplier,
    wallet_dump,
)
from .stat_explainers import STAT_KEYS, explain_stat  # noqa: F401
from .avatar import (  # noqa: F401
    DEFAULT_AVATAR,
    avatar_url,
    reset_avatar,
    save_avatar,
)
from .leagues import (  # noqa: F401
    LEAGUE_TIERS,
    LEAGUE_TOP_N_REWARDED,
    WEEKLY_REWARDS,
    close_league_week,
    ensure_current_week,
    league_state,
    tier_for_xp,
    week_start_for,
    weekly_xp_map,
    weekly_xp_rows,
)
from .challenges import (  # noqa: F401
    active_challenge,
    calories_burned_in_window,
    challenge_state,
    metric_progress,
)
from .social import (  # noqa: F401
    FLOCK_MAX_MEMBERS,
    create_flock,
    friends_of,
    get_friendship,
    invite_to_flock,
    leave_flock,
    membership_of,
    remove_friend,
    respond_flock_invite,
    respond_friend_request,
    search_users,
    send_friend_request,
    social_state,
)
